'use client'; 

import { ShieldCheck, Lock, FileText, Users } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import React from "react"; 

export default function DataPrivacyPage() {
  const [lastUpdated, setLastUpdated] = React.useState('');

  React.useEffect(() => {
    // Set date on client-side to avoid hydration mismatch
    setLastUpdated(new Date().toLocaleDateString());
  }, []);


  return (
    <div className="space-y-12">
      <header className="text-center py-12">
        <ShieldCheck className="h-16 w-16 text-primary mx-auto mb-6" />
        <h1 className="text-4xl font-bold tracking-tight">Data Privacy at TextTransformer</h1>
        <p className="mt-4 text-xl text-muted-foreground max-w-2xl mx-auto">
          Your trust and data privacy are paramount to us. This page explains how we handle your data when you use TextTransformer.
        </p>
      </header>

      <section className="max-w-3xl mx-auto space-y-8">
        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center gap-4">
            <Lock className="h-8 w-8 text-primary" />
            <CardTitle className="text-2xl">Our Commitment to Your Privacy</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground space-y-4">
            <p>
              TextTransformer is designed to process your text inputs to provide AI-powered transformations. We understand the sensitivity of the information you might process through our tools and are committed to handling it responsibly.
            </p>
            <p>
              Our core principle is data minimization: we only process and retain data that is essential for the functioning of our services and for improving your experience.
            </p>
          </CardContent>
        </Card>

        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center gap-4">
            <FileText className="h-8 w-8 text-primary" />
            <CardTitle className="text-2xl">What Data We Process</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground space-y-4">
            <p>
              <strong>Text Inputs:</strong> When you use our AI tools, the text you provide is sent to our AI models for processing. This is necessary to perform transformations like summarization, translation, or content generation.
            </p>
            <p>
              <strong>Generated Outputs:</strong> The results generated by our AI tools are displayed back to you.
            </p>
            <p>
              <strong>Usage Data:</strong> We may collect anonymized usage data (e.g., which tools are used, frequency of use) to improve our services, identify popular features, and troubleshoot issues. This data does not include your specific text inputs.
            </p>
          </CardContent>
        </Card>

        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center gap-4">
            <ShieldCheck className="h-8 w-8 text-primary" />
            <CardTitle className="text-2xl">Data Storage and Retention</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground space-y-4">
            <p>
              <strong>Temporary Processing:</strong> Your text inputs and the AI-generated outputs are typically processed in real-time and are not stored permanently on our servers by default. Once the transformation is complete and displayed to you, the data associated with that specific request is generally discarded from active memory or queued for deletion shortly thereafter.
            </p>
            <p>
              <strong>No Long-Term Storage of Transformed Texts (Default):</strong> We do not build profiles based on your text inputs or store your transformed texts for long periods unless a specific feature (like a user-activated history) requires it, and in such cases, you will be explicitly informed.
            </p>
            <p>
              <strong>Data Security:</strong> We implement industry-standard security measures to protect data during transmission and processing.
            </p>
          </CardContent>
        </Card>
        
        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center gap-4">
            <FileText className="h-8 w-8 text-primary" />
            <CardTitle className="text-2xl">Third-Party Services</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground space-y-4">
            <p>
              TextTransformer utilizes AI models which may be hosted by third-party providers. We ensure that these providers adhere to strict data privacy and security standards. Your data is only shared with these providers to the extent necessary to perform the requested AI transformation.
            </p>
          </CardContent>
        </Card>

        <Card className="shadow-lg">
          <CardHeader className="flex flex-row items-center gap-4">
            <Users className="h-8 w-8 text-primary" />
            <CardTitle className="text-2xl">Your Rights</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground space-y-4">
            <p>
              You have the right to understand how your data is used. If you have any questions or concerns about your data privacy, please contact us.
            </p>
          </CardContent>
        </Card>
      </section>

      <section className="text-center py-12">
        <p className="text-muted-foreground">
          This policy may be updated from time to time. We encourage you to review it periodically.
          {lastUpdated ? ` Last updated: ${lastUpdated}.` : ' Loading update date...'}
        </p>
      </section>
    </div>
  );
}
